---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-app
  template:
    metadata:
      labels:
        app: github-actions-app
    spec:
      initContainers:
        - command:
            - "/bin/sh"
            - "-c"
            - "echo 'Success Message from GitHub Actions!' > /github-actions-app/hello-world"
          image: busybox
          name: github-actions-app
          volumeMounts:
            - mountPath: /github-actions-app
              name: github-actions-app
      containers:
        - command:
            - "/bin/sh"
            - "-c"
            - "while true; do cat /github-actions-app/hello-world; sleep 5; done"
          image: busybox
          name: github-actions-app-1
          volumeMounts:
            - mountPath: /github-actions-app
              name: github-actions-app
      volumes:
        - emptyDir: {}
          name: github-actions-app
